# Generated by Django 5.0.3 on 2024-03-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('process_leader', 'Process Leader'), ('accounting_manager', 'Accounting Manager'), ('requester', 'Requester'), ('reviewer', 'Reviewer'), ('approver', 'Approver')], default='requester', max_length=20),
        ),
    ]
