# Generated by Django 5.0.3 on 2024-03-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_mgmt', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='id_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
