# Generated by Django 5.0.3 on 2024-03-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_mgmt', '0005_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
