# Generated by Django 5.0.3 on 2024-03-30 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_mgmt', '0007_customuser_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='needs_approval',
            field=models.BooleanField(default=True),
        ),
    ]
