# Generated by Django 5.0.3 on 2024-03-18 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeAccountRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='Not Set', max_length=20)),
                ('document_type', models.CharField(default='Not Set', max_length=20)),
                ('user_id', models.CharField(max_length=30)),
                ('amount', models.FloatField(default=0)),
                ('concept', models.CharField(max_length=200)),
                ('costs_and_deductions', models.BooleanField(default=True)),
                ('rent_tax_declarant', models.BooleanField(default=True)),
                ('fiscal_resident', models.BooleanField(default=False)),
                ('city', models.CharField(default='Not Set', max_length=20)),
                ('date', models.DateField(default='Not Set')),
                ('bank_name', models.CharField(default='Not Set', max_length=20)),
                ('account_type', models.CharField(default='Not Set', max_length=20)),
                ('account_number', models.CharField(default='Not Set', max_length=20)),
                ('CEX_no', models.CharField(default='Not Set', max_length=20)),
            ],
        ),
    ]
