# Generated by Django 5.0.3 on 2024-03-30 22:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_mgmt', '0002_chargeaccountrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceRequest',
            fields=[
                ('request_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='requests_mgmt.request')),
            ],
            bases=('requests_mgmt.request',),
        ),
        migrations.CreateModel(
            name='InvoiceLegalizationRequest',
            fields=[
                ('request_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='requests_mgmt.request')),
            ],
            bases=('requests_mgmt.request',),
        ),
        migrations.CreateModel(
            name='TravelExpenseRequest',
            fields=[
                ('request_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='requests_mgmt.request')),
            ],
            bases=('requests_mgmt.request',),
        ),
        migrations.RemoveField(
            model_name='request',
            name='format',
        ),
        migrations.RenameField(
            model_name='chargeaccountrequest',
            old_name='CEX_no',
            new_name='cex_no',
        ),
        migrations.RemoveField(
            model_name='chargeaccountrequest',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='chargeaccountrequest',
            name='id',
        ),
        migrations.RemoveField(
            model_name='chargeaccountrequest',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='chargeaccountrequest',
            name='user_name',
        ),
        migrations.AddField(
            model_name='chargeaccountrequest',
            name='request_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='requests_mgmt.request'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requesttype',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests_mgmt.chargeaccountrequest'),
        ),
        migrations.DeleteModel(
            name='Documents',
        ),
        migrations.DeleteModel(
            name='Format',
        ),
    ]
