# Generated by Django 5.0.3 on 2024-03-30 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_mgmt', '0003_advancerequest_invoicelegalizationrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='requests_mgmt.requeststatus'),
        ),
        migrations.DeleteModel(
            name='RequestType',
        ),
    ]
