# Generated by Django 5.0.3 on 2024-03-30 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_mgmt', '0003_alter_chargeaccountrequest_costs_and_deductions'),
        ('users_mgmt', '0007_customuser_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_requests', to='users_mgmt.customuser'),
        ),
    ]
