# Generated by Django 5.0.3 on 2024-03-31 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_mgmt', '0005_request_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargeaccountrequest',
            name='costs_and_deductions',
            field=models.CharField(default='Not Set', max_length=200),
        ),
    ]
