# Generated by Django 5.0.3 on 2024-04-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_mgmt', '0007_invoicelegalizationrequest_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancerequest',
            name='advance_currency',
            field=models.CharField(default='Not Set', max_length=200),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='advance_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='airport_transport',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='alojamiento',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='departure_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='dependency',
            field=models.CharField(default='Not Set', max_length=200),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='destination_city',
            field=models.CharField(default='Not Set', max_length=200),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='food_expense',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='icesi_last_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='local_transport',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='other_expenses',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='payment_order_code',
            field=models.CharField(default='Not Set', max_length=200),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='reason_trip',
            field=models.CharField(default='Not Set', max_length=200),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='request_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='return_date',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
