# Generated by Django 5.0.3 on 2024-04-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_mgmt', '0008_advancerequest_advance_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advancerequest',
            old_name='alojamiento',
            new_name='accommodation',
        ),
        migrations.RenameField(
            model_name='advancerequest',
            old_name='food_expense',
            new_name='feeding',
        ),
        migrations.RenameField(
            model_name='advancerequest',
            old_name='icesi_last_date',
            new_name='icesi_last_day_date',
        ),
        migrations.RenameField(
            model_name='advancerequest',
            old_name='other_expenses',
            new_name='others',
        ),
        migrations.RenameField(
            model_name='advancerequest',
            old_name='advance_total',
            new_name='widget',
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='departure_taxes',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='advancerequest',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advancerequest',
            name='request_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advancerequest',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
