# Generated by Django 5.0.3 on 2024-04-29 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_mgmt', '0009_rename_alojamiento_advancerequest_accommodation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubro', models.CharField(default='Not Set', max_length=200)),
                ('proveedor', models.CharField(default='Not Set', max_length=200)),
                ('nit', models.CharField(default='Not Set', max_length=200)),
                ('concepto', models.CharField(default='Not Set', max_length=200)),
                ('advance_currency', models.CharField(default='Not Set', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('request_id_number', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='requests_mgmt.request')),
            ],
        ),
    ]
