# Generated by Django 5.0.3 on 2024-05-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_mgmt', '0011_expense_coment'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargeaccountrequest',
            name='bank_certificate_file_path',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='chargeaccountrequest',
            name='rut_file_path',
            field=models.CharField(default='', max_length=250),
        ),
    ]
