# Generated by Django 5.0.3 on 2024-05-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_mgmt', '0012_chargeaccountrequest_bank_certificate_file_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancerequest',
            name='document_path',
            field=models.CharField(default='', max_length=350),
        ),
        migrations.AddField(
            model_name='invoicelegalizationrequest',
            name='document_path',
            field=models.CharField(default='', max_length=350),
        ),
    ]
